// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: player.sql

package godb

import (
	"context"
	"database/sql"
)

const createPlayer = `-- name: CreatePlayer :execresult
INSERT INTO players (username, pw_hash) VALUES (?, ?)
`

type CreatePlayerParams struct {
	Username string
	PwHash   string
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (sql.Result, error) {
	return q.exec(ctx, q.createPlayerStmt, createPlayer, arg.Username, arg.PwHash)
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, username, pw_hash FROM players WHERE id = ?
`

func (q *Queries) GetPlayer(ctx context.Context, id int64) (Player, error) {
	row := q.queryRow(ctx, q.getPlayerStmt, getPlayer, id)
	var i Player
	err := row.Scan(&i.ID, &i.Username, &i.PwHash)
	return i, err
}

const getPlayerByUsername = `-- name: GetPlayerByUsername :one
SELECT id, username, pw_hash FROM players WHERE username = ?
`

func (q *Queries) GetPlayerByUsername(ctx context.Context, username string) (Player, error) {
	row := q.queryRow(ctx, q.getPlayerByUsernameStmt, getPlayerByUsername, username)
	var i Player
	err := row.Scan(&i.ID, &i.Username, &i.PwHash)
	return i, err
}

const getPlayerPWHash = `-- name: GetPlayerPWHash :one
SELECT (pw_hash) FROM players WHERE id = ?
`

func (q *Queries) GetPlayerPWHash(ctx context.Context, id int64) (string, error) {
	row := q.queryRow(ctx, q.getPlayerPWHashStmt, getPlayerPWHash, id)
	var pw_hash string
	err := row.Scan(&pw_hash)
	return pw_hash, err
}
