name: "Migrate Production DB"
on:
  push:
    branches:
      - main
jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Create branch
      uses: planetscale/create-branch-action@v1
      id: create_branch
      with:
        org_name: oil 
        database_name: well
        branch_name: cd
        from: main
      env:
        PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
        PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
    - name: Create a deploy request
      uses: planetscale/create-deploy-request-action@v1
      id: create_deploy_request
      with:
        org_name: oil
        database_name: well
        branch_name: cd
      env:
        PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
        PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
    - name: Deploy a deploy request
      uses: planetscale/deploy-deploy-request-action@v1
      with:
        org_name: oil
        database_name: well 
        number: ${{ steps.create_deploy_request.outputs.number }}
        wait: true
      env:
        PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
        PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
