name: Go Test
on: [push]
jobs:
  test:
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
    runs-on: ubuntu-latest
    steps:
          - name: Setup Atlas
            uses: ariga/setup-atlas@v0
          - name: Checkout
            uses: actions/checkout@v4
          - name: Setup Go
            uses: actions/setup-go@v4
            with:
              go-version: 1.21.x
          - name: Run Tests
            run: go test ./...
