name: Integration Tests
on: [workflow_call]
jobs:
  app:
    name: Website
    runs-on: ubuntu-latest
    steps:
      - name: Create password
        uses: planetscale/create-branch-password-action@v3
        id: create_password
        with:
          org_name: oil
          database_name: well
          branch_name: cd
          name: cd-integ-tests-app
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
      # - name: Checkout App
        # uses: actions/checkout@v4
        # with:
          # repository: afteralec/app.oil
      # - name: Setup Go
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version: 1.21.x
      # - name: Integration Tests
      #   run:
      #     go test ./tests/...
      #   env:
      #     DATABASE_URL: ${{ steps.create_password.outputs.username }}:${{ steps.create_password.outputs.password }}@${{ steps.create_password.outputs.hostname }}/well?tls=true
