name: Integration Tests
on: [workflow_call]
jobs:
    test:
      name: Integration Tests
      needs: create-cd-database
      runs-on: ubuntu-latest
      steps:
        - name: Create password
          uses: planetscale/create-branch-password-action@v3
          id: create_password
          with:
            org_name: oil
            database_name: well
            branch_name: cd
            name: cd-integ-tests-app
          env:
            PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
            PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
        - name: Echo credentials
          run: |
            echo "${{ steps.create_password.outputs.username }}"
