name: "Migrate Production DB"
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/*"
      - "migrations/*"
jobs:
    tests:
      uses: ./.github/workflows/test.yaml
    migrate:
      uses: ./.github/workflows/create-cd-db.yaml
      needs: [tests]
