name: "Migrate Production DB"
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/*"
      - "migrations/*"
jobs:
    test:
      uses: ./.github/workflows/test.yaml
    create-cd-db:
      needs: [test]
      runs-on: ubuntu-latest
      steps:
      - name: Create branch
        uses: planetscale/create-branch-action@v4
        id: create_branch
        with:
          org_name: oil
          database_name: well
          branch_name: cd
          from: main
          wait: true
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
      - name: Create password
        uses: planetscale/create-branch-password-action@v3
        id: create_password
        with:
          org_name: oil
          database_name: well
          branch_name: cd
          name: cd-migrate
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
      - name: Setup Atlas
        uses: ariga/setup-atlas@v0
      - name: Checkout
        uses: actions/checkout@v4
      - name: Apply Migrations
        run: |
          atlas migrate apply -u "mysql://${{ steps.create_password.outputs.username }}:${{ steps.create_password.outputs.password }}@${{ steps.create_password.outputs.hostname }}/well?tls=true"
